apiVersion: v1
kind: Namespace
metadata:
  name: vendcar
---
apiVersion: v1
kind: Secret
metadata:
  name: vendcar-secrets
  namespace: vendcar
type: Opaque
stringData:
  db-password: vendcar123
  jwt-secret: vendcar-jwt-secret-prod
